# Generated by Django 4.2.30 on 2026-05-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('director', 'Director'), ('administrativo', 'Administrativo'), ('medico', 'Médico'), ('especialista', 'Especialista'), ('farmacia', 'Farmacia'), ('paciente_portal', 'Paciente Portal')], max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('ambos', 'Ambos')], default='manana', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
