# Generated by Django 4.2.30 on 2026-05-25 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('viudo', 'Viudo/a'), ('divorciado', 'Divorciado/a')], max_length=20)),
                ('ocupacion', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=50)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('idioma_principal', models.CharField(default='español', max_length=30)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
    ]
