# Generated by Django 4.2.30 on 2026-05-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('presentacion', models.CharField(blank=True, max_length=100)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=10)),
                ('unidad', models.CharField(default='unidades', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medicamentos',
                'ordering': ['nombre'],
            },
        ),
    ]
