# Generated by Django 4.2.30 on 2026-05-25 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto')], default='presencial', max_length=15)),
                ('turno', models.CharField(choices=[('manana', 'Mañana'), ('tarde', 'Tarde')], max_length=10)),
                ('estado', models.CharField(choices=[('esperando', 'Esperando'), ('llamado', 'Llamado'), ('atendiendo', 'Atendiendo'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado')], default='esperando', max_length=15)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_llamado', models.DateTimeField(blank=True, null=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('tiempo_espera_est', models.IntegerField(blank=True, null=True)),
                ('posicion_cola', models.IntegerField(blank=True, null=True)),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_emitidos', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['fecha_emision'],
            },
        ),
    ]
