# Generated by Django 4.2.30 on 2026-05-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_slot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='franja_horaria',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
