# Generated by Django 4.2.30 on 2026-05-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreceta',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='itemreceta',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='itemreceta',
            name='frecuencia',
        ),
        migrations.AddField(
            model_name='itemreceta',
            name='cantidad_dispensada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemreceta',
            name='cantidad_recetada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemreceta',
            name='indicaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='itemreceta',
            name='valor_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
