# Generated by Django 4.2.30 on 2026-05-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_remove_itemreceta_dosis_remove_itemreceta_duracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreceta',
            name='indicaciones',
        ),
        migrations.AddField(
            model_name='itemreceta',
            name='cantidad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='itemreceta',
            name='frecuencia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='itemreceta',
            name='tiempo_uso',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
