# Generated by Django 4.2.30 on 2026-05-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0003_remove_itemreceta_indicaciones_itemreceta_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreceta',
            name='via_administracion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
