# Generated by Django 4.2.30 on 2026-05-25 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('especialidad', 'Especialidad')], default='general', max_length=15)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada')], default='activa', max_length=15)),
                ('derivado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_derivadas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_medico', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pacientes.paciente')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='tickets.ticket')),
            ],
            options={
                'db_table': 'consultas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('saturacion_oxigeno', models.IntegerField(blank=True, null=True)),
                ('glucosa', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to='consultas.consulta')),
            ],
            options={
                'db_table': 'signos_vitales',
            },
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad_destino', models.CharField(max_length=100)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=15)),
                ('fecha_derivacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('notas_especialista', models.TextField(blank=True, null=True)),
                ('consulta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones', to='consultas.consulta')),
                ('medico_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones_destino', to=settings.AUTH_USER_MODEL)),
                ('medico_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_origen', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'derivaciones',
                'ordering': ['-fecha_derivacion'],
            },
        ),
    ]
