# Generated by Django 4.2.30 on 2026-05-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='nivel_dolor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='sintomas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
